from django.conf import settings
from django.db import models
from products.models import ProductVariant
class Order(models.Model):
    STATUS=[(x,x.replace('_',' ').title()) for x in ['placed','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled','return_requested','returned','refund_initiated','refunded']]
    PAYMENT=[('cod','Cash on Delivery'),('online','Online')]
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='orders'); order_id=models.CharField(max_length=30,unique=True); status=models.CharField(max_length=30,choices=STATUS,default='placed'); payment_method=models.CharField(max_length=20,choices=PAYMENT,default='cod'); payment_status=models.CharField(max_length=30,default='pending');
    shipping_name=models.CharField(max_length=120); shipping_phone=models.CharField(max_length=20); shipping_line1=models.CharField(max_length=200); shipping_city=models.CharField(max_length=100); shipping_state=models.CharField(max_length=100); shipping_pincode=models.CharField(max_length=10)
    subtotal=models.DecimalField(max_digits=12,decimal_places=2); discount=models.DecimalField(max_digits=12,decimal_places=2,default=0); shipping_fee=models.DecimalField(max_digits=12,decimal_places=2,default=0); tax=models.DecimalField(max_digits=12,decimal_places=2,default=0); total=models.DecimalField(max_digits=12,decimal_places=2); tracking_number=models.CharField(max_length=120,blank=True); expected_delivery=models.DateField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
class OrderItem(models.Model): order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items'); variant=models.ForeignKey(ProductVariant,on_delete=models.PROTECT); product_name=models.CharField(max_length=220); size=models.CharField(max_length=30,blank=True); color=models.CharField(max_length=50,blank=True); quantity=models.PositiveIntegerField(); unit_price=models.DecimalField(max_digits=12,decimal_places=2); discount=models.DecimalField(max_digits=12,decimal_places=2,default=0)
class Payment(models.Model): order=models.OneToOneField(Order,on_delete=models.CASCADE,related_name='payment'); gateway=models.CharField(max_length=40,default='razorpay'); gateway_order_id=models.CharField(max_length=150,blank=True); gateway_payment_id=models.CharField(max_length=150,blank=True); amount=models.DecimalField(max_digits=12,decimal_places=2); status=models.CharField(max_length=30,default='created'); created_at=models.DateTimeField(auto_now_add=True)
